<h1><?php echo $this->title; ?></h1>

<h2>Below you can find information about used technologies and projects</h2>

<h3>Technologies:</h3>
<ul class="list technologies">
    <li>
        <strong>Zend Framework 1.12.3</strong><br />
        <a href="http://framework.zend.com/">http://framework.zend.com/</a>
    </li>
    <li>
        <strong>Blueprint: A CSS Framework</strong><br />
        <a href="http://www.blueprintcss.org/">http://www.blueprintcss.org/</a>
    </li>
    <li>
        <strong>jQuery 1.9.1</strong><br />
        <a href="http://jquery.com/">http://jquery.com/</a>
    </li>
    <li>
        <strong>Silk icon set 1.3</strong><br />
        <a href="http://www.famfamfam.com/lab/icons/silk/">http://www.famfamfam.com/lab/icons/silk/</a>
    </li>
    <li>
        <strong>Bijou icon set</strong><br />
        <a href="http://bijou.im/">http://bijou.im/</a>
    </li>

</ul>

<h3>References:</h3>
<ul class="list references">
    <li>
        <strong>Zend_Form: Building dynamic forms by Tibo Beijen</strong><br />
        <a href="http://www.tibobeijen.nl/blog/2009/12/21/zend_form-building-dynamic-forms/">http://www.tibobeijen.nl/blog/2009/12/21/zend_form-building-dynamic-forms/</a>
    </li>
    <li>
        <strong>Zend_Form_Dynamic by Tibo Beijen</strong><br />
        <a href="http://www.tibobeijen.nl/static/zend_form_dynamic/">http://www.tibobeijen.nl/static/zend_form_dynamic/</a>
    </li>

    <li>
        <strong>HTML5 Tags in IE8</strong><br />
        <a href="http://www.nickyeoman.com/blog/html/118-html5-tags-in-ie8">http://www.nickyeoman.com/blog/html/118-html5-tags-in-ie8</a>
    </li>
    <li>
        <strong>Html colors names</strong><br />
        <a href="http://www.w3schools.com/html/html_colornames.asp">http://www.w3schools.com/html/html_colornames.asp</a>
    </li>
    <li>
        <strong>CSS2 Selectors</strong><br />
        <a href="http://www.w3.org/TR/CSS2/selector.html#pattern-matching">http://www.w3.org/TR/CSS2/selector.html#pattern-matching</a>
    </li>
    <li>
        <strong>CSS3 Selectors</strong><br />
        <a href="http://www.w3.org/TR/css3-selectors/#selectors">http://www.w3.org/TR/css3-selectors/#selectors</a>
    </li>
</ul>