<h1><?php echo $this->title; ?></h1>

<h2>Below you can find information about used technologies and projects</h2>

<h3>Technologies:</h3>
<ul class="list technologies">
    <li>
        <strong>Zend Framework 1.12.3</strong><br />
        <a href="http://framework.zend.com/">http://framework.zend.com/</a>
    </li>
    <li>
        <strong>Blueprint: A CSS Framework</strong><br />
        <a href="http://www.blueprintcss.org/">http://www.blueprintcss.org/</a>
    </li>
    <li>
        <strong>jQuery 1.9.1</strong><br />
        <a href="http://jquery.com/">http://jquery.com/</a>
    </li>
    <li>
        <strong>Google Maps JavaScript API v3</strong><br />
        <a href="https://developers.google.com/maps/documentation/javascript/?hl=pl">https://developers.google.com/maps/documentation/javascript/?hl=pl</a>
    </li>
    <li>
        <strong>Silk icon set 1.3</strong><br />
        <a href="http://www.famfamfam.com/lab/icons/silk/">http://www.famfamfam.com/lab/icons/silk/</a>
    </li>
    <li>
        <strong>Bijou icon set</strong><br />
        <a href="http://bijou.im/">http://bijou.im/</a>
    </li>
</ul>

<h3>References:</h3>
<ul class="list references">
    <li>
        <strong>Documentation of Drawing Tools from the Google Maps</strong><br />
        <a href="https://developers.google.com/maps/documentation/javascript/examples/drawing-tools?hl=pl">https://developers.google.com/maps/documentation/javascript/examples/drawing-tools?hl=pl</a>
    </li>
    <li>
        <strong>How to find co-ordinates from google map api to display markers from database in map</strong><br />
        <a href="http://stackoverflow.com/questions/13177617/how-to-find-co-ordinates-from-google-map-api-to-display-markers-from-database-in">http://stackoverflow.com/questions/13177617/how-to-find-co-ordinates-from-google-map-api-to-display-markers-from-database-in</a>
    </li>

    <li>
        <strong>HTML5 Tags in IE8</strong><br />
        <a href="http://www.nickyeoman.com/blog/html/118-html5-tags-in-ie8">http://www.nickyeoman.com/blog/html/118-html5-tags-in-ie8</a>
    </li>
    <li>
        <strong>Html colors names</strong><br />
        <a href="http://www.w3schools.com/html/html_colornames.asp">http://www.w3schools.com/html/html_colornames.asp</a>
    </li>
    <li>
        <strong>CSS2 Selectors</strong><br />
        <a href="http://www.w3.org/TR/CSS2/selector.html#pattern-matching">http://www.w3.org/TR/CSS2/selector.html#pattern-matching</a>
    </li>
    <li>
        <strong>CSS3 Selectors</strong><br />
        <a href="http://www.w3.org/TR/css3-selectors/#selectors">http://www.w3.org/TR/css3-selectors/#selectors</a>
    </li>
</ul>