<?php echo $this->partial('partials/init-maps.phtml', array()); ?>

<?php $this->headScript()->captureStart() ?>
function initialize() {
  var mapOptions = {
    center: new google.maps.LatLng(-34.397, 150.644),
    zoom: 8,
    mapTypeId: google.maps.MapTypeId.ROADMAP
  };
  var map = new google.maps.Map(document.getElementById("map-canvas"), mapOptions);
}
google.maps.event.addDomListener(window, 'load', initialize);
<?php $this->headScript()->captureEnd() ?>


<h1><?php echo $this->title; ?></h1>

<h2>West Coast of Australia - Sydney area</h2>

<div id="map-canvas" />
