<h1><?php echo $this->title; ?></h1>

<?php echo $this->form; ?>

<?php if ($_POST): ?>
<p class="<?php if (!$this->valid) { echo 'error'; } ?>">The form is <?php echo $this->valid ? '' : 'not '; ?>valid</p>
<?php endif; ?>

<?php if ($this->messages): ?>
<p class="label"><strong>Form error messages</strong>:</p>
<pre>
<?php print_r($this->messages); ?>
</pre>
<?php endif; ?>

<?php if ($this->values): ?>
<p class="label"><strong>Form values</strong>:</p>
<pre>
<?php print_r($this->values); ?>
</pre>
<?php endif; ?>

<?php if ($_POST): ?>
<p class="label"><strong>POST</strong>:</p>
<pre>
<?php print_r($_POST); ?>
</pre>
<?php endif; ?>